use soroban_sdk::contracterror;

/// Shared error codes used across all Vaulty contracts.
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    Unauthorized = 1,
    VaultNotFound = 2,
    InvalidAmount = 3,
    InsufficientBalance = 4,
    VaultLocked = 5,
    InvalidLockPeriod = 6,
    Overflow = 7,
    Underflow = 8,
    InvalidAsset = 9,
    AlreadyInitialized = 10,
    NotInitialized = 11,
    InvalidTimestamp = 12,
    StreakNotFound = 13,
    LoanNotFound = 14,
    InsufficientCollateral = 15,
    LiquidationThreshold = 16,
    RewardAlreadyClaimed = 17,
    InvalidParameters = 18,
    PoolNotFound = 19,
    PoolAlreadyExists = 20,
    InsufficientLiquidity = 21,
    InvalidInterestRate = 22,
    InvalidShareAmount = 23,
    PoolPaused = 24,
    PoolClosed = 25,
    ZeroShares = 26,
    InsufficientShares = 27,
    InvalidReserveFactor = 28,
    RateLimitExceeded = 29,
    EmergencyStopActive = 30,
    PermissionDenied = 31,
    LoanAlreadyExists = 32,
    InvalidCollateral = 33,
    CollateralRatioTooLow = 34,
    FlashLoanNotAllowed = 35,
    CooldownPeriodNotMet = 36,
    InvalidTimestampRange = 37,
    ContractPaused = 38,
    ReentrancyDetected = 39,
    InvalidSignature = 40,
    ExpiredDeadline = 41,
    StorageExpired = 42,
    DuplicateActivity = 43,
    NoFreezesAvailable = 44,
    MilestoneAlreadyReached = 45,
    RewardsPoolNotInitialized = 46,
    RewardsPoolAlreadyInitialized = 47,
    InsufficientRewardLiquidity = 48,
    UnauthorizedAdmin = 49,
    RewardNotEligible = 50,
    PoolAlreadyInitialized = 51,
    LoanAlreadyRepaid = 52,
    LiquidationNotAllowed = 53,
    NoPositionFound = 54,
}

