[workspace]
resolver = "2"
members = [
    "vault",
    "streaks",
    "rewards",
    "shared",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
soroban-sdk = "21.7.6"
shared = { path = "shared" }
vault = { path = "vault" }
streaks = { path = "streaks" }
rewards = { path = "rewards" }

[patch.crates-io]
ethnum = { path = "./ethnum-patch" }
