[package]
name = "vault"
version.workspace = true
edition.workspace = true

[dependencies]
soroban-sdk.workspace = true
shared.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
streaks = { path = "../streaks" }
rewards = { path = "../rewards" }

[features]
integration_tests = []