[package]
name = "rewards"
version.workspace = true
edition.workspace = true

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk.workspace = true
shared.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
rewards = { path = ".", features = ["testutils"] }
